Test failing

diff --git a/.github/workflows/basic-workflow.yml b/.github/workflows/basic-workflow.yml
--- a/.github/workflows/basic-workflow.yml
+++ b/.github/workflows/basic-workflow.yml
@@ -10,3 +10,7 @@ jobs:
     steps:
       - name: The Thing I've Done
         run: echo "I've done a thing!"
+      - name: An Error I Made
+        run: |
+          echo "I've made an error!"
+          exit 1
